# Workflow to build and deploy a COMPLETE OpenWrt package repository.
# **FULL SOURCE BUILD VERSION**
# This workflow builds the default package set for each target, plus all custom packages.

name: Build and Deploy PeDitXOS OpenWrt Packages (Full Source)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openwrt_version:
          - 'openwrt-24.10'
          - 'master'
          - 'openwrt-23.05'
          - 'openwrt-22.03'
        
        # **CORRECTED MATRIX SYNTAX**: Using a simple list of strings, which is valid.
        target_subtarget:
          - 'ath79/generic'
          - 'bcm27xx/bcm2711'
          - 'ipq40xx/generic'
          - 'ipq806x/generic'
          - 'ipq807x/generic'
          - 'lantiq/xrx200'
          - 'mediatek/filogic'
          - 'mvebu/cortexa9'
          - 'ramips/mt7621'
          - 'rockchip/armv8'
          - 'sunxi/cortexa7'
          - 'x86/64'
          - 'qualcommax/ipq5018'
          - 'qualcommax/ipq6018'
          - 'qualcommax/ipq8074'
          - 'realtek/generic'
          - 'mediatek/mt7622'

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion libncurses5-dev gawk zlib1g-dev python3-dev python3-setuptools unzip wget libtool python3-pip
          pip3 install pyelftools

      - name: Clone OpenWrt source code
        run: git clone --depth 1 --branch ${{ matrix.openwrt_version }} https://github.com/openwrt/openwrt.git openwrt

      - name: Clone custom single packages directly
        run: |
          git clone --depth 1 https://github.com/peditx/luci-app-themeswitch.git openwrt/package/luci-app-themeswitch
          git clone --depth 1 https://github.com/peditx/luci-theme-peditx.git openwrt/package/luci-theme-peditx
          git clone --depth 1 https://github.com/peditx/luci-theme-carbonpx.git openwrt/package/luci-theme-carbonpx

      - name: Add custom feeds and generate config
        run: |
          cd openwrt
          
          echo 'src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages' >> feeds.conf.default
          echo 'src-git passwall_peditx https://github.com/peditx/openwrt-passwall' >> feeds.conf.default
          echo 'src-git passwall2_peditx https://github.com/peditx/openwrt-passwall2' >> feeds.conf.default
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # **CORRECTED LOGIC**: Parse the simple string from the matrix into two variables.
          TARGET_MAIN="${{ matrix.target_subtarget }}"
          TARGET=$(echo "$TARGET_MAIN" | cut -d'/' -f1)
          SUBTARGET=$(echo "$TARGET_MAIN" | cut -d'/' -f2)
          
          # Set the target architecture using the parsed variables.
          cat > .config << EOF
          CONFIG_TARGET_${TARGET}=y
          CONFIG_TARGET_${TARGET}_${SUBTARGET}=y
          EOF
          
          # Generate the default config for the selected target
          make defconfig
          
          # Add custom package selections and signing options to resolve warnings
          cat >> .config << EOF
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_libpam=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_liblzma=y
          CONFIG_PACKAGE_libnetsnmp=y
          CONFIG_SIGNED_PACKAGES=y
          EOF
          
          # Sync the config to include all available packages and their dependencies
          make oldconfig

      - name: Cache OpenWrt Downloads
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-${{ matrix.openwrt_version }}-dl-${{ hashFiles('openwrt/feeds.conf.default') }}

      - name: Decode usign private key
        run: |
          echo "${{ secrets.USIGN_PRIVATE_KEY }}" | base64 -d > openwrt/signing_key.pem
          echo "CONFIG_SIGNATURE_KEY=\"signing_key.pem\"" >> openwrt/.config

      - name: Download package sources
        run: |
          cd openwrt
          make download -j$(nproc)

      - name: Cache Host Tools
        uses: actions/cache@v4
        with:
          path: openwrt/staging_dir/host
          key: ${{ runner.os }}-${{ matrix.openwrt_version }}-host-${{ hashFiles('openwrt/.config') }}

      - name: Build host tools (including usign)
        run: |
          cd openwrt
          make tools/install -j$(nproc) V=s
      
      - name: Build target toolchain
        run: |
          cd openwrt
          make toolchain/install -j$(nproc) V=s

      - name: Build packages
        run: |
          cd openwrt
          # This command builds all packages selected in the .config (default set + custom packages)
          make package/compile -j$(nproc) V=s
          # This command creates the index for the packages we just built
          make package/index V=s

      - name: Organize packages for artifact upload
        run: |
          # **CORRECTED LOGIC**: Parse the string again for creating the directory structure.
          TARGET_MAIN="${{ matrix.target_subtarget }}"
          TARGET=$(echo "$TARGET_MAIN" | cut -d'/' -f1)
          SUBTARGET=$(echo "$TARGET_MAIN" | cut -d'/' -f2)
          
          mkdir -p "dist/${{ matrix.openwrt_version }}/${TARGET}/${SUBTARGET}/packages"
          find openwrt/bin/packages -type f -name "*.ipk" -exec cp {} "dist/${{ matrix.openwrt_version }}/${TARGET}/${SUBTARGET}/packages/" \;
          find openwrt/bin/targets -name "Packages*" -exec cp {} "dist/${{ matrix.openwrt_version }}/${TARGET}/${SUBTARGET}/" \;
          cp openwrt/key-build.pub "dist/${{ matrix.openwrt_version }}/"
          
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all built packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./dist
      
      - name: Create a root index.html file
        run: |
          cd dist
          echo '<!DOCTYPE html><html><head><title>PeDitXOS Repository</title><style>body{font-family: sans-serif; padding: 2em;}</style></head><body>' > index.html
          echo '<h1>PeDitXOS Repository</h1>' >> index.html
          echo '<h2>Available OpenWrt Versions:</h2><ul>' >> index.html
          
          for dir in $(find . -maxdepth 1 -type d -not -name '.*' -not -name '.' | sort); do
            version_name=$(basename "$dir")
            echo "<li><a href=\"$version_name/\">$version_name</a></li>" >> index.html
          done
          
          echo '</ul>' >> index.html
          
          find . -name 'key-build.pub' -print -exec cp {} ./key-build.pub \; -quit
          
          echo '<h3>Public Signing Key: <a href="key-build.pub">key-build.pub</a></h3>' >> index.html
          echo '</body></html>'
          
      - name: Push updates to main repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: peditx/PeDitXOS-Repository
          publish_dir: ./dist
          publish_branch: repo
          force_orphan: true
          cname: downloads.peditxos.ir

      - name: Final Check
        run: echo "Deployment to 'peditx/PeDitXOS-Repository' branch 'repo' complete."

